version: '3'
services:
  database:
    build: ./db
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=${DB_ROOT_HOST}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - dbvolume:/var/lib/mysql
  backend:
    build: ./server
    container_name: server
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - database
    links:
      - database:database
volumes:
  dbvolume: